#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

setxkbmap us -option ctrl:nocaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[ -x $HOME/.fehbg ] && $HOME/.fehbg
[ -f $HOME/.xinitrc.env ] && source $HOME/.xinitrc.env
[ -x $HOME/.xinitrc.local ] && $HOME/.xinitrc.local

DIR=$XDG_RUNTIME_DIR/status
mkdir -p $DIR

killall dwmstatus
dwmstatus $DIR &

exec dwm
